# Generated by Django 4.2.16 on 2024-11-05 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Naam van de kortingsregel",
                        max_length=255,
                        verbose_name="Naam",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optionele beschrijving van de kortingsregel",
                        verbose_name="Beschrijving",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is deze kortingsregel momenteel actief?",
                        verbose_name="Actief",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Wanneer gaat de korting in?",
                        verbose_name="Startdatum",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Wanneer eindigt de korting? Leeg = geen einddatum",
                        null=True,
                        verbose_name="Einddatum",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Vast bedrag"),
                        ],
                        max_length=20,
                        verbose_name="Type korting",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of vast bedrag van de korting",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kortingswaarde",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Hogere waarde = hogere prioriteit bij overlappende regels",
                        verbose_name="Prioriteit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kortingsregel",
                "verbose_name_plural": "Kortingsregels",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Fabrikant"),
                            ("category", "Categorie"),
                            ("tag", "Tag"),
                            ("property", "Eigenschap"),
                            ("price", "Prijsbereik"),
                        ],
                        max_length=20,
                        verbose_name="Type voorwaarde",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="JSON waarde voor de voorwaarde",
                        verbose_name="Waarde",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[("AND", "EN"), ("OR", "OF")],
                        default="AND",
                        max_length=3,
                        verbose_name="Operator",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="discounts.discountrule",
                        verbose_name="Kortingsregel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kortingsvoorwaarde",
                "verbose_name_plural": "Kortingsvoorwaarden",
            },
        ),
    ]
